---
# tasks file for centos-mt
- name: Adding Prometheus repository
  copy:
    src: prometheus.repo
    dest: /etc/yum.repos.d/

- name: Installing Prometheus
  yum:
    name: prometheus2
    state: latest
    update_cache: yes

- name: Starting Prometheus
  service:
    name: prometheus
    state: started
