---
# tasks file for centos-es
- name: Installing FTP server on CentOS
  yum:
   name: vsftpd
   state: latest
   update_cache: yes

- name: Starting the FTP service
  service:
   name: vsftpd
   state: started
   enabled: yes

- name: Creating an FTP User
  user:
   name: '{{ user }}'
   password: '{{ ftp_pass }}'

- name: Denying user to Access SSH
  lineinfile:
   path: /etc/ssh/sshd_config
   line: "DenyUsers '{{ user }}'"
  register: successfully_denied

- name: Restarting SSHd service
  service:
   name: sshd
   state: restarted
  when: successfully_denied.changed

- name: Copying the default configuration file
  copy:
   src: /etc/vsftpd/vsftpd.conf
   dest: /etc/vsftpd/vsftpd.conf.default
   remote_src: True
 
- name: Limiting the FTP users to their own home directory
  replace:
   path: /etc/vsftpd/vsftpd.conf
   regexp: '#chroot_local_user=YES'
   replace: 'chroot_local_user=YES'

- name: Configuring FTP file
  lineinfile:
   path: /etc/vsftpd/vsftpd.conf
   line: '{{ ftp_config }}'

- name: Restarting vsftpd
  service:
   name: vsftpd
   state: restarted
